server:
 port: 8081
spring:
 cloud:
  config:
   server:
    git:
     default-label: development
     uri: https://github.com/devmeste/scooter-app
     search-paths: config-data
 application:
  name: mcsv-config
